language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

matrix:
  include:
    - python: 3.7
      dist: xenial

install: python setup.py install

before_script: pip install nose

script:
  - python runtests.py -v
  - nosetests -v

